apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: carrental
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/carrental"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "1234"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SERVER_PORT: "8080"

