apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: carrental
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_DATABASE: "carrental"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "1234"

